# Aula 08 &mdash; Análise exploratória de dados

Renato Vimieiro
rv2 {em} cin.ufpe.br

abril 2017

## Introdução

Vimos na aula anterior a segunda etapa para análise de dados que consistia na limpeza, integração e pré-processamento dos dados coletados. Terminada essa etapa, seguimos para uma exploração inicial dos dados para nos familiarizarmos com eles. Essa etapa é importante para detectarmos falhas na coleta, validar premissas, avaliar possíveis relações entre os atributos e determinar a direção (escolha dos modelos) que utilizaremos na análise. Essa etapa é conhecida como Análise Exploratória dos Dados, tendo sido proposta pelo estatístico John Tukey em 1977 com a publicação do livro de mesmo nome (em inglês *Exploratory Data Analysis*).

John Tukey convenceu os estatísticos da época que essa etapa deveria preceder o emprego de qualquer modelo estatístico para análise dos dados. A principal característica da análise exploratória de dados é o uso de estatísticas descritivas e gráficos para entender relações ocultas presentes nos dados.

Como discutimos anteriormente, o modelo/paradigma científico anterior era baseado em hipóteses. Dados eram coletados a fim de verificar a validade dessas hipóteses. Dessa forma, a compreensão das relações presentes nos dados era valiosa para levantar outras hipóteses a serem testadas. Essa mesma razão é ainda mais pertinente no paradigma atual centrado em dados. A maior parte dos dados são coletados arbitrariamente sem uma clara intenção de validar uma hipótese. Isso faz com que a análise exploratória dos dados seja ainda mais valiosa para justamente possibilitar que hipóteses sejam levantadas, assim como para entender o que foi coletado.

Uma das ideias mais defendidas por Tukey para análise exploratória de dados é a do uso de gráficos para facilitar a compreensão. Veremos na aula de hoje os diversos tipos de visualizações disponíveis para cada tipo de atributo, assim como uma revisão de estatísticas descritivas.

Usaremos como exemplo as séries históricas sobre a expectativa de vida no nascimento e produto interno bruto dos países coletadas pelo Banco Mudial. Os dados estão disponíveis nos links: [expectativa de vida](http://data.worldbank.org/indicator/SP.DYN.LE00.IN) e [PIB](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD).

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

% matplotlib inline

In [10]:
expvida = pd.read_csv("../2017.1/data/banco_mudial/life_expectancy.csv",index_col=0,
                      skiprows=[0,1,2],)
expvida = expvida.drop(['Indicator Name', 'Indicator Code', 
                        'Country Code'],axis=1).dropna(axis=1,how='all')
expvida.head()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,65.569366,65.988024,66.365537,66.713976,67.044293,67.369756,67.699000,68.034683,68.377146,68.728415,...,74.228073,74.376195,74.526756,74.675732,74.818146,74.953537,75.081390,75.205756,75.328659,75.451098
Afghanistan,32.328512,32.777439,33.219902,33.657878,34.092878,34.525390,34.957415,35.389415,35.822415,36.260390,...,57.027244,57.432561,57.833829,58.225024,58.603683,58.970829,59.327951,59.679610,60.028268,60.374463
Angola,32.984829,33.386220,33.787585,34.188463,34.590341,34.992220,35.395098,35.799976,36.205854,36.610244,...,48.538805,49.007049,49.435732,49.847390,50.251024,50.654171,51.059317,51.464000,51.866171,52.266878
Albania,62.254366,63.273463,64.162854,64.887098,65.438195,65.827390,66.089317,66.287220,66.474951,66.681610,...,76.081610,76.286122,76.470293,76.652073,76.840366,77.036951,77.240585,77.443976,77.640463,77.830463
Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
gdp = pd.read_csv("../2017.1/data/banco_mudial/gdp.csv",index_col=0,
                      skiprows=[0,1,2],)
gdp = gdp.drop(['Indicator Name', 'Indicator Code', 
                'Country Code', '2015'],axis=1).dropna(axis=1,how='all')
gdp.head()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.331006e+09,2.421475e+09,2.623726e+09,2.791961e+09,2.498933e+09,2.467704e+09,2.584464e+09,NaN,NaN,NaN
Afghanistan,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,1.400000e+09,1.673333e+09,1.373333e+09,1.408889e+09,...,6.275074e+09,7.057598e+09,9.843842e+09,1.019053e+10,1.248694e+10,1.593680e+10,1.793024e+10,2.053654e+10,2.004633e+10,2.005019e+10
Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.823371e+10,4.178948e+10,6.044892e+10,8.417803e+10,7.549238e+10,8.247091e+10,1.041159e+11,1.153984e+11,1.249121e+11,1.267769e+11
Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.158549e+09,8.992642e+09,1.070101e+10,1.288135e+10,1.204421e+10,1.192695e+10,1.289087e+10,1.231978e+10,1.278103e+10,1.321986e+10
Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.248215e+09,3.536633e+09,4.010991e+09,4.001201e+09,3.650083e+09,3.346517e+09,3.427023e+09,3.146152e+09,3.248925e+09,NaN

In [98]:
expv_pib = pd.merge(expvida,gdp,left_index=True, right_index=True, suffixes=['_ev','_pib'])
expv_pib = expv_pib.reset_index()
expv_pib  = pd.melt(expv_pib,id_vars='Country Name')
expv_pib.rename(columns={'Country Name':'country'}, inplace=True)
expv_pib.set_index('country',inplace=True)
expv_pib.head(15)

                     variable      value
country
Aruba                 1960_ev  65.569366
Afghanistan           1960_ev  32.328512
Angola                1960_ev  32.984829
Albania               1960_ev  62.254366
Andorra               1960_ev        NaN
Arab World            1960_ev  46.850022
United Arab Emirates  1960_ev  52.243220
Argentina             1960_ev  65.215537
Armenia               1960_ev  65.863463
American Samoa        1960_ev        NaN
Antigua and Barbuda   1960_ev  61.782732
Australia             1960_ev  70.817073
Austria               1960_ev  68.585610
Azerbaijan            1960_ev  60.836244
Burundi               1960_ev  41.236049

## Revisão estatísticas descritivas

A forma mais usada para descrever e sumarizar um conjunto de dados é através da avaliação da tendência central de um atributo e sua variabilidade ou dispersão. As medidas mais comuns de tendência central são: *média (aritmética)*, *mediana*, *moda* e o ponto médio do intervalo. Já as medidas de dispersão são: desvio padrão, variância, amplitude, quantil, e amplitude/intervalo interquartil.

#### Média aritmética

A média artimética de uma amostra é dada pela fórmula:

$$
\bar{v} = \frac{\sum v[i]}{N}
$$

Em Pandas, como já vimos anteriormente, ela é calculada através do método `mean`. Por exemplo, podemos calcular a expectativa de vida média mundial da seguinte forma:

In [114]:
expvida.mean(axis=0)

1960    53.316972
1961    53.870082
1962    54.264033
1963    54.641853
1964    55.134160
1965    55.621615
1966    56.088514
1967    56.515384
1968    56.913283
1969    57.298899
1970    57.778240
1971    58.115587
1972    58.511045
1973    58.950935
1974    59.269638
1975    59.636184
1976    60.011477
1977    60.394363
1978    60.827633
1979    61.136480
1980    61.534375
1981    61.895084
1982    62.386842
1983    62.640375
1984    62.982854
1985    63.289699
1986    63.674581
1987    64.046644
1988    64.174422
1989    64.398744
1990    64.623422
1991    64.843291
1992    65.011648
1993    65.061818
1994    65.329304
1995    65.483428
1996    65.755696
1997    66.085685
1998    66.211192
1999    66.437642
2000    66.762516
2001    67.052200
2002    67.429526
2003    67.612203
2004    67.997679
2005    68.305760
2006    68.702235
2007    69.081031
2008    69.444249
2009    69.813421
2010    70.099730
2011    70.476308
2012    70.696585
2013    70.965698
2014    71.245815
dtype: float64

#### Mediana

Embora a média aritmética seja frequentemente para sumarizar um atributo, ela é muito sensível a valores extremos. A presença de um único valor extremo na amostra pode deslocar bastante a média, fazendo com que ela não seja informativa. Essa situação também ocorre com dados assimétricos (distribuições com uma das caudas mais pesada). Nesse caso, o valor que divide a sequência na metade é mais representativo. Esse valor é a mediana. A mediana, ao contrário da média, pode ser obtida tanto para atributos numéricos quanto para ordinais.

A mediana é obtida em Pandas com o método `median`. Podemos obter a mediana do PIB mundial como abaixo. Perceba como a média é deslocada em função do PIB dos países mais ricos.

In [37]:
gdp.apply(lambda x: pd.Series({'mediana': x.median(), 'media': x.mean()})).T

             media       mediana
1960  7.120347e+10  2.037151e+09
1961  7.393467e+10  2.088012e+09
1962  7.839931e+10  2.224868e+09
1963  8.496941e+10  2.583687e+09
1964  9.349347e+10  2.782474e+09
1965  9.774862e+10  2.793218e+09
1966  1.058608e+11  2.876396e+09
1967  1.103924e+11  2.869407e+09
1968  1.155847e+11  3.201439e+09
1969  1.273173e+11  3.529741e+09
1970  1.334579e+11  3.120019e+09
1971  1.443843e+11  3.872858e+09
1972  1.670410e+11  4.468150e+09
1973  2.048221e+11  5.281699e+09
1974  2.375791e+11  7.680104e+09
1975  2.605385e+11  7.841458e+09
1976  2.793974e+11  9.030262e+09
1977  3.098103e+11  9.355692e+09
1978  3.645926e+11  1.034550e+10
1979  4.221517e+11  1.041705e+10
1980  4.483871e+11  1.015396e+10
1981  4.478113e+11  8.661264e+09
1982  4.458401e+11  9.240000e+09
1983  4.558556e+11  8.836000e+09
1984  4.656820e+11  9.701357e+09
1985  4.800454e+11  1.000550e+10
1986  5.618757e+11  1.023488e+10
1987  6.271937e+11  1.052734e+10
1988  6.890933e+11  1.041611e+10
1989  7.233168e+11  1.036228e+10
1990  7.622509e+11  1.229057e+10
1991  8.060123e+11  1.134148e+10
1992  8.443227e+11  1.139631e+10
1993  8.442709e+11  1.318095e+10
1994  8.918799e+11  1.289916e+10
1995  9.615238e+11  1.335047e+10
1996  9.860830e+11  1.384365e+10
1997  9.892436e+11  1.474460e+10
1998  9.780026e+11  1.498897e+10
1999  1.000029e+12  1.492598e+10
2000  1.011896e+12  1.376037e+10
2001  1.009242e+12  1.381270e+10
2002  1.048959e+12  1.480319e+10
2003  1.186172e+12  1.782544e+10
2004  1.341986e+12  2.120635e+10
2005  1.468775e+12  2.618879e+10
2006  1.604473e+12  3.021606e+10
2007  1.837086e+12  3.411310e+10
2008  2.056086e+12  4.278520e+10
2009  1.957496e+12  4.206622e+10
2010  2.177742e+12  4.405093e+10
2011  2.446024e+12  4.765470e+10
2012  2.547354e+12  5.182157e+10
2013  2.628796e+12  5.664499e+10
2014  2.762845e+12  5.797893e+10

#### Moda

A moda é o valor mais frequente em um atributo. Ela pode ser calculada tanto para atributos numéricos quanto categóricos. Note que um atributo pode ter mais de um valor mais frequente. Nesse caso, dizemos que o atributo é **bimodal** (duas) ou **multimodal** (várias modas). Quando todos os valores têm a mesma frequência, então o atributo não possui moda.

Em Pandas ela é calcula pela função `mode`. Para exemplificar, vamos discretizar a expectativa de vida em *baixa* [0,50), *média* [50,70) e *alta* [70,inf), e, em seguida, calcular a moda.

In [45]:
expvida.apply(lambda x: pd.cut(x,bins=[0,50,70,np.infty],right=False)).mode().T

              0
1960   [50, 70)
1961   [50, 70)
1962   [50, 70)
1963   [50, 70)
1964   [50, 70)
1965   [50, 70)
1966   [50, 70)
1967   [50, 70)
1968   [50, 70)
1969   [50, 70)
1970   [50, 70)
1971   [50, 70)
1972   [50, 70)
1973   [50, 70)
1974   [50, 70)
1975   [50, 70)
1976   [50, 70)
1977   [50, 70)
1978   [50, 70)
1979   [50, 70)
1980   [50, 70)
1981   [50, 70)
1982   [50, 70)
1983   [50, 70)
1984   [50, 70)
1985   [50, 70)
1986   [50, 70)
1987   [50, 70)
1988   [50, 70)
1989   [50, 70)
1990   [50, 70)
1991   [50, 70)
1992   [50, 70)
1993   [50, 70)
1994   [50, 70)
1995   [50, 70)
1996   [50, 70)
1997   [50, 70)
1998   [50, 70)
1999  [70, inf)
2000  [70, inf)
2001  [70, inf)
2002  [70, inf)
2003  [70, inf)
2004  [70, inf)
2005  [70, inf)
2006  [70, inf)
2007  [70, inf)
2008  [70, inf)
2009  [70, inf)
2010  [70, inf)
2011  [70, inf)
2012  [70, inf)
2013  [70, inf)
2014  [70, inf)

#### Variância e desvio padrão

A variância e desvio padrão indicam quão espalhada é a distribuição dos dados. Desvios padrão mais baixos indicam que os dados estão mais concentrados perto da média, enquanto valores mais altos indicam maior amplitude de valores.

O desvio padrão de uma amostra é calculado por:

$$
\sigma_v = \sqrt{\frac{1}{N}\sum (v[i] - \bar{v})^2}
$$

Em Pandas, como já vimos, ele é obtido por `std`. Como exemplo, vamos calcular a média e desvio padrão da expectativa de vida dos países.

In [52]:
expvida.apply(lambda x: pd.Series({'media':x.mean(), 'desvp':x.std()}, 
                              index=['media','desvp']),axis=1)

                                                        media      desvp
Country Name
Aruba                                               72.009732   2.738927
Afghanistan                                         46.871411   9.148672
Angola                                              41.851346   5.308439
Albania                                             71.246746   4.093708
Andorra                                                   NaN        NaN
Arab World                                          61.024869   7.497234
United Arab Emirates                                68.820820   7.074375
Argentina                                           70.749239   3.504606
Armenia                                             70.316793   2.325032
American Samoa                                            NaN        NaN
Antigua and Barbuda                                 69.923561   4.161397
Australia                                           76.063947   3.947829
Austria                                             74.732993   4.010781
Azerbaijan                                          65.756648   2.538131
Burundi                                             48.290789   4.200675
Belgium                                             75.067503   3.466472
Benin                                               49.982449   6.900854
Burkina Faso                                        46.979641   6.875524
Bangladesh                                          57.660148   8.480861
Bulgaria                                            71.624084   1.180425
Bahrain                                             69.590544   6.626039
Bahamas, The                                        69.615921   3.593087
Bosnia and Herzegovina                              70.376880   4.425167
Belarus                                             69.819016   1.122167
Belize                                              68.104451   3.042333
Bermuda                                             77.622164   3.600314
Bolivia                                             54.181093   8.058512
Brazil                                              64.807168   5.919131
Barbados                                            69.676153   4.248293
Brunei Darussalam                                   71.674379   4.526383
...                                                       ...        ...
Latin America & the Caribbean (IDA & IBRD count...  66.193773   5.810838
Timor-Leste                                         48.144183  12.378711
Middle East & North Africa (IDA & IBRD countries)   61.587495   8.229225
Tonga                                               68.260691   3.242705
South Asia (IDA & IBRD)                             56.415401   7.702862
Sub-Saharan Africa (IDA & IBRD countries)           48.866060   4.580167
Trinidad and Tobago                                 67.300077   1.932776
Tunisia                                             63.468760  10.678343
Turkey                                              62.041620   9.092217
Tuvalu                                                    NaN        NaN
Tanzania                                            50.965893   5.351550
Uganda                                              48.614232   3.808850
Ukraine                                             69.221696   1.050126
Upper middle income                                 65.699634   6.894365
Uruguay                                             72.065835   2.971958
United States                                       74.461774   2.895459
Uzbekistan                                          65.250732   2.578769
St. Vincent and the Grenadines                      68.063870   3.822522
Venezuela, RB                                       68.748199   4.200324
British Virgin Islands                                    NaN        NaN
Virgin Islands (U.S.)                               73.103758   4.953413
Vietnam                                             68.188942   5.672938
Vanuatu                                             60.940992   7.713914
World                                               63.722157   5.282044
Samoa                                               62.944187   7.300075
Kosovo                                              68.304161   1.304467
Yemen, Rep.                                         52.435930   9.676421
South Africa                                        55.732976   3.949706
Zambia                                              48.558585   4.565202
Zimbabwe                                            53.010113   6.525704

[264 rows x 2 columns]

#### Amplitude

A amplitude de um atributo é a diferença entre o menor e maior valor. Ela pode ser calculada por uma função simples, ou através do método `ptp` (peak to peak) de `pandas.Series`. Por exemplo, podemos avaliar a variação do PIB ao longo dos anos.

In [116]:
gdp.apply(lambda x: pd.Series({'amplitude': x.ptp(), 'min':x.min(), 'max':x.max()})).T

         amplitude           max           min
1960  1.352922e+12  1.352934e+12  1.201203e+07
1961  1.408308e+12  1.408320e+12  1.159202e+07
1962  1.507685e+12  1.507694e+12  9.122751e+06
1963  1.628576e+12  1.628587e+12  1.084010e+07
1964  1.786698e+12  1.786711e+12  1.271247e+07
1965  1.946918e+12  1.946931e+12  1.359393e+07
1966  2.110107e+12  2.110121e+12  1.446908e+07
1967  2.253148e+12  2.253164e+12  1.583518e+07
1968  2.429354e+12  2.429368e+12  1.460000e+07
1969  2.672066e+12  2.672081e+12  1.585000e+07
1970  2.936435e+12  2.936449e+12  1.429528e+07
1971  3.242203e+12  3.242218e+12  1.527863e+07
1972  3.748849e+12  3.748868e+12  1.893653e+07
1973  4.561595e+12  4.561619e+12  2.419602e+07
1974  5.244792e+12  5.244823e+12  3.151486e+07
1975  5.838358e+12  5.838391e+12  3.250674e+07
1976  6.338916e+12  6.338946e+12  3.003642e+07
1977  7.164536e+12  7.164570e+12  3.413939e+07
1978  8.438105e+12  8.438147e+12  4.156747e+07
1979  9.816364e+12  9.816407e+12  4.262017e+07
1980  1.107237e+13  1.107241e+13  3.871555e+07
1981  1.133919e+13  1.133923e+13  3.102000e+07
1982  1.121781e+13  1.121785e+13  3.491800e+07
1983  1.159202e+13  1.159206e+13  3.783784e+07
1984  1.201678e+13  1.201682e+13  4.124616e+07
1985  1.264371e+13  1.264375e+13  3.212515e+07
1986  1.496806e+13  1.496810e+13  3.208556e+07
1987  1.703077e+13  1.703081e+13  3.360874e+07
1988  1.906539e+13  1.906544e+13  4.297211e+07
1989  2.001072e+13  2.001076e+13  4.111972e+07
1990  2.251651e+13  2.251652e+13  8.824448e+06
1991  2.385173e+13  2.385174e+13  9.365166e+06
1992  2.534292e+13  2.534293e+13  9.742949e+06
1993  2.578579e+13  2.578580e+13  9.630763e+06
1994  2.775009e+13  2.775010e+13  1.088683e+07
1995  3.084779e+13  3.084780e+13  1.102595e+07
1996  3.152869e+13  3.152870e+13  1.233485e+07
1997  3.141216e+13  3.141217e+13  1.270091e+07
1998  3.131576e+13  3.131578e+13  1.275763e+07
1999  3.248788e+13  3.248790e+13  1.368714e+07
2000  3.354757e+13  3.354758e+13  1.374206e+07
2001  3.334277e+13  3.334279e+13  1.319654e+07
2002  3.461742e+13  3.461743e+13  1.545099e+07
2003  3.887595e+13  3.887597e+13  1.823108e+07
2004  4.377913e+13  4.377915e+13  2.153493e+07
2005  4.739173e+13  4.739175e+13  2.183910e+07
2006  5.131057e+13  5.131059e+13  2.290286e+07
2007  5.775632e+13  5.775634e+13  2.043329e+07
2008  6.334507e+13  6.334510e+13  3.029022e+07
2009  6.004395e+13  6.004397e+13  2.710108e+07
2010  6.585313e+13  6.585316e+13  3.182352e+07
2011  7.317263e+13  7.317267e+13  3.931202e+07
2012  7.468176e+13  7.468180e+13  3.987575e+07
2013  7.677607e+13  7.677611e+13  3.832236e+07
2014  7.863009e+13  7.863013e+13  3.725969e+07

#### Quantil e amplitude interquartil

Os quantis são valores retirados da amostra que dividem os valores em intervalos com a mesma frequência (mesma quantidade de elementos). A mediana, por exemplo, divide os dados em dois intervalos iguais. Logo, ela é equivalente a 2-quantil. O 4-quantil, ou **quartil**, são os três valores da amostra que dividem o intervalo em quatro partes com a mesma quantidade de elementos. Finalmente, o 100-quantil é o conjunto de pontos que dividem os dados em 100 intervalos com a mesma quantidade de elementos, sendo chamados **percentis**.

Pandas oferece suporte direto para obtermos esses valores. A função `quantile` espera como parâmtro uma lista de percentis. Exemplo:

In [59]:
expvida.quantile([0.25, .5, .75]).T

           0.25       0.50       0.75
1960  43.568488  52.475280  63.761963
1961  44.225994  53.385537  64.321970
1962  44.819985  54.289159  64.731751
1963  45.321005  54.910195  64.966694
1964  45.915841  55.387293  65.391231
1965  46.638945  55.896852  65.708360
1966  47.253622  56.356311  66.046768
1967  47.770750  57.067614  66.467811
1968  48.225049  57.693280  66.967018
1969  48.563878  58.506294  67.444213
1970  49.016415  59.282634  68.055927
1971  49.412561  59.900915  68.217805
1972  49.810226  60.500024  68.360854
1973  50.207293  60.912146  68.883902
1974  50.512340  61.376783  68.668720
1975  51.145505  61.550610  68.973878
1976  51.771101  62.061634  69.160787
1977  52.418293  62.313817  69.460360
1978  53.003489  63.062483  69.655854
1979  53.548600  63.533202  69.841634
1980  54.092801  63.680736  69.868254
1981  54.373935  64.099276  70.149140
1982  54.920197  64.699961  70.475796
1983  55.317420  65.035447  70.434318
1984  55.741049  65.444615  70.494866
1985  56.166672  65.793215  70.770585
1986  56.683109  66.268307  71.130372
1987  57.275043  66.855064  71.434341
1988  57.302926  66.928451  71.471280
1989  57.799501  67.415832  71.465976
1990  58.373494  67.638617  71.362866
1991  58.642524  67.897558  71.746768
1992  58.926579  67.792524  71.821543
1993  58.920407  67.475488  71.935854
1994  58.969874  67.763976  72.196500
1995  59.126437  68.015439  72.269024
1996  59.306841  68.523756  72.596256
1997  59.657732  68.901854  72.940988
1998  59.412598  68.966415  73.345768
1999  59.731884  69.274024  73.577049
2000  60.235388  69.999341  73.752293
2001  60.290585  70.258537  74.500927
2002  60.888000  70.690732  74.717317
2003  61.103268  70.845768  74.609817
2004  61.487896  71.106988  74.931201
2005  62.386156  71.253659  75.044329
2006  63.135675  71.460220  75.187671
2007  63.873743  71.697122  75.378543
2008  64.262877  71.889073  75.591043
2009  64.640010  72.139451  75.905006
2010  64.943427  72.304366  76.108872
2011  65.173256  72.487195  76.355615
2012  65.346104  72.606427  76.448665
2013  65.678957  72.765707  76.800967
2014  65.951683  72.936854  76.986146

A diferença entre o terceiro e o primeiro quartil é chamada de **amplitude interquartil** (IQR). Como o primeiro e terceiro quartis definem os valores tais que 25% e 75% dos dados estão abaixo deles, a diferença entre os dois fornece a amplitude do intervalo que cobre 50% dos valores. Isso nos dá uma ideia de quão espalhados são os dados. Podemos calcular o IQR aplicando uma função que calcule a diferença dos quartis.

In [60]:
expvida.apply(lambda x: x.quantile(0.75) - x.quantile(0.25))

1960    20.193476
1961    20.095976
1962    19.911766
1963    19.645689
1964    19.475390
1965    19.069415
1966    18.793146
1967    18.697061
1968    18.741970
1969    18.880335
1970    19.039512
1971    18.805244
1972    18.550628
1973    18.676610
1974    18.156380
1975    17.828373
1976    17.389686
1977    17.042067
1978    16.652364
1979    16.293035
1980    15.775452
1981    15.775205
1982    15.555599
1983    15.116898
1984    14.753817
1985    14.603914
1986    14.447263
1987    14.159299
1988    14.168354
1989    13.666475
1990    12.989372
1991    13.104244
1992    12.894963
1993    13.015446
1994    13.226626
1995    13.142587
1996    13.289415
1997    13.283256
1998    13.933171
1999    13.845165
2000    13.516905
2001    14.210341
2002    13.829317
2003    13.506549
2004    13.443305
2005    12.658173
2006    12.051995
2007    11.504800
2008    11.328165
2009    11.264996
2010    11.165445
2011    11.182359
2012    11.102561
2013    11.122009
2014    11.034463
dtype: float64

Embora as estatísticas acima forneçam uma ideia da dispersão dos dados, todas podem falhar, sobretudo, com dados assimétricos. Dessa forma, é muito comum o **resumo de cinco números** que contém os valores mínimo e máximo do atributo, além do primeiro, segundo (mediana) e terceiro quartis. Se notarmos, essa é a estatística descritiva retornada pelo método `describe`, o qual ainda acrescenta a média, desvio padrão e a quantidade de valores não-nulos.

In [62]:
expvida.describe().T

,count,mean,std,min,25%,50%,75%,max
1960,235.0,53.316972,11.819422,28.211610,43.568488,52.475280,63.761963,73.549756
1961,236.0,53.870082,11.828587,28.358732,44.225994,53.385537,64.321970,73.652683
1962,236.0,54.264033,11.689797,28.548463,44.819985,54.289159,64.731751,73.721951
1963,235.0,54.641853,11.583371,28.796390,45.321005,54.910195,64.966694,73.555366
1964,235.0,55.134160,11.547545,29.111049,45.915841,55.387293,65.391231,73.733171
1965,236.0,55.621615,11.429417,29.501927,46.638945,55.896852,65.708360,73.868780
1966,236.0,56.088514,11.343648,29.970976,47.253622,56.356311,66.046768,74.078537
1967,236.0,56.515384,11.222269,30.505634,47.770750,57.067614,66.467811,74.122439
1968,236.0,56.913283,11.077837,31.093780,48.225049,57.693280,66.967018,74.005854
1969,236.0,57.298899,10.938343,31.726415,48.563878,58.506294,67.444213,74.084878
1970,237.0,57.778240,10.874455,32.393000,49.016415,59.282634,68.055927,74.649268
1971,236.0,58.115587,10.780703,33.081512,49.412561,59.900915,68.217805,74.623902
1972,236.0,58.511045,10.723404,33.785000,49.810226,60.500024,68.360854,74.718049
1973,237.0,58.950935,10.693110,32.812878,50.207293,60.912146,68.883902,74.867317
1974,236.0,59.269638,10.646682,28.258488,50.512340,61.376783,68.668720,74.980488
1975,236.0,59.636184,10.623407,23.884537,51.145505,61.550610,68.973878,75.578780
1976,236.0,60.011477,10.597988,20.656512,51.771101,62.061634,69.160787,76.972195
1977,236.0,60.394363,10.553734,19.265512,52.418293,62.313817,69.460360,76.373659
1978,238.0,60.827633,10.446621,20.064927,53.003489,63.062483,69.655854,76.649268
1979,237.0,61.136480,10.293123,23.029098,53.548600,63.533202,69.841634,76.773171
1980,238.0,61.534375,10.120552,27.738976,54.092801,63.680736,69.868254,76.846585
1981,238.0,61.895084,9.963285,33.449927,54.373935,64.099276,70.149140,76.521463
1982,242.0,62.386842,9.803920,38.186220,54.920197,64.699961,70.475796,77.037805
1983,239.0,62.640375,9.690835,39.666488,55.317420,65.035447,70.434318,76.961463
1984,239.0,62.982854,9.614115,39.999537,55.741049,65.444615,70.494866,77.576585
1985,239.0,63.289699,9.529507,40.324805,56.166672,65.793215,70.770585,77.650488
1986,240.0,63.674581,9.530650,39.886268,56.683109,66.268307,71.130372,78.064634
1987,244.0,64.046644,9.477522,39.330659,57.275043,66.855064,71.434341,78.483659
1988,240.0,64.174422,9.517636,38.694073,57.302926,66.928451,71.471280,78.399268
1989,240.0,64.398744,9.569034,38.018585,57.799501,67.415832,71.465976,78.818049
1990,242.0,64.623422,9.582743,33.485122,58.373494,67.638617,71.362866,78.836829
1991,243.0,64.843291,9.645045,29.745829,58.642524,67.897558,71.746768,79.100732
1992,244.0,65.011648,9.667101,27.483659,58.926579,67.792524,71.821543,79.153902
1993,241.0,65.061818,9.705718,27.078902,58.920407,67.475488,71.935854,79.293659
1994,243.0,65.329304,9.744893,28.568122,58.969874,67.763976,72.196500,79.687073
1995,243.0,65.483428,9.684162,31.634512,59.126437,68.015439,72.269024,79.536341
1996,243.0,65.755696,9.729078,35.659195,59.306841,68.523756,72.596256,80.200244
1997,247.0,66.085685,9.703275,36.426195,59.657732,68.901854,72.940988,80.424146
1998,243.0,66.211192,9.779394,37.046805,59.412598,68.966415,73.345768,80.501463
1999,244.0,66.437642,9.785452,37.812537,59.731884,69.274024,73.577049,80.570732
2000,247.0,66.762516,9.789939,38.690146,60.235388,69.999341,73.752293,81.076098
2001,245.0,67.052200,9.863487,39.645488,60.290585,70.258537,74.500927,81.424390
2002,249.0,67.429526,9.780320,40.642902,60.888000,70.690732,74.717317,81.563415
2003,246.0,67.612203,9.700922,40.702488,61.103268,70.845768,74.609817,81.760000
2004,246.0,67.997679,9.646001,41.059341,61.487896,71.106988,74.931201,82.030244
2005,247.0,68.305760,9.452554,41.759610,62.386156,71.253659,75.044329,81.975610
2006,247.0,68.702235,9.305500,42.810707,63.135675,71.460220,75.187671,82.375610
2007,248.0,69.081031,9.100834,44.177756,63.873743,71.697122,75.378543,82.507073
2008,248.0,69.444249,8.919874,45.739244,64.262877,71.889073,75.591043,82.831707
2009,248.0,69.813421,8.744318,46.634585,64.640010,72.139451,75.905006,82.995543
2010,246.0,70.099730,8.604553,47.483415,64.943427,72.304366,76.108872,83.159379
2011,247.0,70.476308,8.487421,48.219756,65.173256,72.487195,76.355615,83.421951
2012,246.0,70.696585,8.312338,48.836000,65.346104,72.606427,76.448665,83.480488
2013,244.0,70.965698,8.237375,48.937927,65.678957,72.765707,76.800967,83.831707
2014,245.0,71.245815,8.123204,48.934732,65.951683,72.936854,76.986146,83.980488

#### Sumarização de dados categóricos

Vimos que a moda e mediana podem ser calculadas para valores categóricos, mas quais outras estatísticas podemos computar para descrever os dados? O mais comum com dados nominais é contar a frequência das categorias, apresentando-as de forma relativa ou absoluta. Também podemos explorar a relação entre dois atributos categóricos, montando uma tabela (tabela de contigência) entre elas. Por exemplo, imagine que estivéssemos trabalhando com dados discretos para a expectativa de vida e PIB. Poderíamos querer investigar qual a relação (se existe alguma) entre a faixa de valores do PIB e a expectativa de vida. Podemos tabular os dois valores e ver a contagem das ocorrências.

In [104]:
df = pd.DataFrame({'expvida':pd.cut(expv_pib[expv_pib.variable.str.contains('1960_ev')].value,bins=[0,50,70,np.infty],right=False),\
                  'pib':pd.qcut(expv_pib[expv_pib.variable.str.contains('1960_pib')].value,q=3)})
df.head()

              expvida                            pib
country
Aruba        [50, 70)                            NaN
Afghanistan   [0, 50)  [12012025.248, 672627041.359]
Angola        [0, 50)                            NaN
Albania      [50, 70)                            NaN
Andorra           NaN                            NaN

In [105]:
pd.crosstab(df.expvida,df.pib)

pib,"[12012025.248, 672627041.359]","(672627041.359, 8180853312.437]","(8180853312.437, 1352934141105.46]"
expvida,,,
"[0, 50)",26,16,20
"[50, 70)",12,21,16
"[70, inf)",1,3,6

In [106]:
df = pd.DataFrame({'expvida':pd.cut(expv_pib[expv_pib.variable.str.contains('2010_ev')].value,bins=[0,50,70,np.infty],right=False),\
                  'pib':pd.qcut(expv_pib[expv_pib.variable.str.contains('2010_pib')].value,q=3)})
pd.crosstab(df.expvida,df.pib)

pib,"[31823518.62, 12829146451.167]","(12829146451.167, 237685681918.125]","(237685681918.125, 65853158964855]"
expvida,,,
"[0, 50)",6,0,0
"[50, 70)",40,27,26
"[70, inf)",27,54,56